name: Launcher

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            artifact-name: Win64
            extension: exe
          - os: ubuntu-latest
            artifact-name: Linux
            extension: deb
          - os: macos-latest
            artifact-name: macOS
            extension: dmg
    name: "Build - ${{ matrix.artifact-name }}"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Packages
        run: npm install
      - name: Build
        run: npm run dist
      - uses: actions/upload-artifact@v2
        with:
          name: XRP-Blockly-Installer-${{ matrix.artifact-name }}
          path: dist/*.${{ matrix.extension }}

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          path: dist
      - name: Upload Release Assets
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          gh release upload --clobber "${GITHUB_REF#refs/tags/}" dist/*/*
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}